export default {
  leaks: false,
  numFailingTests: 0,
  numPassingTests: 1,
  numPendingTests: 0,
  numTodoTests: 2,
  openHandles: [],
  perfStats: {
    end: 1648777582957,
    runtime: 1408,
    slow: false,
    start: 1648777581549,
  },
  skipped: false,
  snapshot: {
    added: 0,
    fileDeleted: false,
    matched: 0,
    unchecked: 0,
    uncheckedKeys: [],
    unmatched: 0,
    updated: 0,
  },
  testFilePath:
    '/Users/scalablepath/magic_auth/modules/app/components/AppWithModulesHocs.test.js',
  testResults: [
    {
      ancestorTitles: ['AppWithModulesHocs'],
      duration: 34,
      failureDetails: [],
      failureMessages: [],
      fullName:
        'AppWithModulesHocs renders successfully (this adds the modules hocs)',
      invocations: 1,
      location: null,
      numPassingAsserts: 0,
      status: 'passed',
      title: 'renders successfully (this adds the modules hocs)',
    },
    {
      ancestorTitles: ['AppWithModulesHocs'],
      duration: null,
      failureDetails: [],
      failureMessages: [],
      fullName: 'AppWithModulesHocs wraps with the store provider',
      invocations: 1,
      location: null,
      numPassingAsserts: 0,
      status: 'todo',
      title: 'wraps with the store provider',
    },
    {
      ancestorTitles: ['AppWithModulesHocs'],
      duration: null,
      failureDetails: [],
      failureMessages: [],
      fullName: 'AppWithModulesHocs wraps with the theme provider',
      invocations: 1,
      location: null,
      numPassingAsserts: 0,
      status: 'todo',
      title: 'wraps with the theme provider',
    },
  ],
  failureMessage: null,
}